[package]
name = "yarn-lock"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]

[dependencies]
log = "0.4"
nom = "3.2"
indent_tokenizer = "0.4.0"
semver = "0.9"
failure = "0.1"
url = { git = "https://github.com/hoodie/rust-url", features = ["serde"] }
multimap = "0.4.0"
